ENH: Added stddef.h include to NumerticTraitsTest
With gcc > 4.6 this header is required to be included to prevent

Change-Id: I2fa8122bd444cf64d9542f3744810116151a0eab
error: expected type-specifier before ‘ptrdiff_t’