COMP: Generate VNL export file correctly with VXL_LIB_PREFIX.
The hard-coded vnl_export.h file does not have the right macros when
VXL_LIB_PREFIX is defined. This breaks VS shared builds with
CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS:BOOL=ON.

Errors like:

C:\Jenkins\src\ITK\Modules\ThirdParty\VNL\src\vxl\core\vnl\vnl_numeric_traits.cxx(71):
error C2491: 'vnl_numeric_traits::maxval': definition of dllimport static data
member not allowed

result.

Change-Id: Ib8192f289cfb5017c68c3038bb85048cfe3d1ccf