COMP: Provide H5CX_set_apl declaration in H5Odeprec.c
LED: Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Odeprec.c.o
/emsdk_portable/emscripten/sdk/emcc -D_GNU_SOURCE -IModules/ThirdParty/ZLIB/src -I/ITK/Modules/ThirdParty/ZLIB/src -I/ITK/Modules/ThirdParty/HDF5/src -IModules/ThirdParty/HDF5/src -I/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src -IModules/ThirdParty/HDF5/src/itkhdf5 -std=c99 -Wno-warn-absolute-paths --memory-init-file 0 -s WASM=0 -lnodefs.js -Wno-almost-asm  -Wno-uninitialized -Wno-unused-parameter -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow  -w -DNDEBUG -O2 -fPIC   -std=gnu99 -MD -MT Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Odeprec.c.o -MF Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Odeprec.c.o.d -o Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Odeprec.c.o   -c /ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Odeprec.c
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Odeprec.c:141:8: error: implicit declaration of function 'itk_H5CX_set_apl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if(H5CX_set_apl(&lapl_id, H5P_CLS_LACC, loc_id, FALSE) < 0)
       ^
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/itk_hdf5_mangle.h:435:22: note: expanded from macro 'H5CX_set_apl'
                     ^
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Odeprec.c:195:8: error: implicit declaration of function 'itk_H5CX_set_apl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if(H5CX_set_apl(&lapl_id, H5P_CLS_LACC, loc_id, FALSE) < 0)
       ^
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/itk_hdf5_mangle.h:435:22: note: expanded from macro 'H5CX_set_apl'
                     ^
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Odeprec.c:322:8: error: implicit declaration of function 'itk_H5CX_set_apl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if(H5CX_set_apl(&lapl_id, H5P_CLS_LACC, loc_id, FALSE) < 0)
       ^
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/itk_hdf5_mangle.h:435:22: note: expanded from macro 'H5CX_set_apl'