ENH: Included itkImageSource.h from itkTestingComparisonImageFilter.h
A very simple example like this:

int main(int, char*[])
{
  typedef itk::Image<float, 2> ImageType;
  typedef itk::Testing::ComparisonImageFilter< ImageType, ImageType > DiffType;

  return EXIT_SUCCESS;
}

would not compile due to:
ITK/include/ITK-4.0/itkTestingComparisonImageFilter.h:42:21: error:
expected template-name before ‘<’ token

Which is this line:
public ImageSource< TOutputImage >

Including ImageSource fixes the problem.

Change-Id: I1512770c0703b5e2dc12a0ce1bea717414b0ea8f