COMP: Provide H5CX_get_ohdr_flags declaration in H5Oint.c
To address:

/emsdk_portable/emscripten/sdk/emcc -D_GNU_SOURCE -IModules/ThirdParty/ZLIB/src -I/ITK/Modules/ThirdParty/ZLIB/src -I/ITK/Modules/ThirdParty/HDF5/src -IModules/ThirdParty/HDF5/src -I/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src -IModules/ThirdParty/HDF5/src/itkhdf5 -std=c99 -Wno-warn-absolute-paths --memory-init-file 0 -s WASM=0 -lnodefs.js -Wno-almost-asm  -Wno-uninitialized -Wno-unused-parameter -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow  -w -DNDEBUG -O2 -fPIC   -std=gnu99 -MD -MT Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Oint.c.o -MF Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Oint.c.o.d -o Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Oint.c.o   -c /ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Oint.c
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Oint.c:358:12: error: implicit declaration of function 'H5CX_get_ohdr_flags' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if(H5CX_get_ohdr_flags(&oh_flags) < 0)
           ^
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Oint.c:358:12: note: did you mean 'H5O_get_oh_flags'?
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Oprivate.h:913:16: note: 'H5O_get_oh_flags' declared here
H5_DLL uint8_t H5O_get_oh_flags(const H5O_t *oh);