COMP: Don't use override and noexcept method specifiers together
Clang 5.0, and c++11 with GCC 4.6, 4.7 all are reporting compiler
errors when these two method specifiers are used together. Only using
the exception specifier resolve the compilation issue.

Addressed the following issue:
itkObject.h:105:16: error: exception specification of overriding
function is more lax than base version
  virtual void UnRegister() const ITK_OVERRIDE ITK_NOEXCEPT;

Change-Id: I83e715dc67968a564965d7ec9ef32f91f6e40d01